[package]
name = "computour"
version = "0.1.0"
authors = ["Nicholas Montano <montanonic@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.85"
once_cell = "1.5.2"
